name: Scenario CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build -x test



      - name: Set environment values
        run: |
          rm -f .env 
          echo "${{ secrets.ENV }}" > .env
        shell: bash

      - name: Show application config
        run: cat .env

      - name: Restore .p12 file
        run: echo "${{ secrets.P12_BASE64 }}" | base64 -d > keystore.p12
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/scenario:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/scenario:latest

      - name: EC2 Docker Run
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop scenario-container || true
            sudo docker rm scenario-container || true
          
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/scenario:latest
            sudo docker run -d --name scenario-container \
              --env-file .env \
              -p 443:443 \
              -e SSL_KEYSTORE_PATH=keystore.p12 \
              -e SSL_KEYSTORE_PASSWORD=${{ secrets.SSL_KEYSTORE_PASSWORD }} \
              -e SSL_KEY_ALIAS=${{ secrets.SSL_KEY_ALIAS }} \
              -e TZ=Asia/Seoul \
              ${{ secrets.DOCKER_USERNAME }}/scenario:latest
