name: senario CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment values
        run: |
          rm -f .env 
          echo "${{ secrets.ENV }}" > .env
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/senario:latest
          platforms: linux/amd64

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            echo "${{ secrets.P12_BASE64 }}" | base64 --decode | sudo tee /opt/certs/keystore.p12 > /dev/null
            sudo chmod 600 /opt/certs/keystore.p12
          
            sudo docker stop senario-container || true
            sudo docker rm senario-container || true

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/senario:latest
            sudo docker run -d --name senario-container \
              --env-file .env \
              -p 443:443 \
              -e SSL_KEYSTORE_PATH=/opt/certs/keystore.p12 \
              -e SSL_KEYSTORE_PASSWORD=${{ secrets.SSL_KEYSTORE_PASSWORD }} \
              -e SSL_KEY_ALIAS=${{ secrets.SSL_KEY_ALIAS }} \
              -e TZ=Asia/Seoul \
              ${{ secrets.DOCKER_USERNAME }}/senario:latest
